spring:
  datasource:
    username: root
    password: Aa123456_
    url: jdbc:dm://192.168.43.228:5236/VSPACE
    driver-class-name: dm.jdbc.driver.DmDriver
mybatis:
  mapper-locations: classpath:com/winemall/mall/mapper/*.xml
logging:
  level:
    com:
      cestc:
        vspace:
          mapper: debug

